don't fail on first failure

diff --git a/communication/task-post-slack.yaml b/communication/task-post-slack.yaml
--- a/communication/task-post-slack.yaml
+++ b/communication/task-post-slack.yaml
@@ -80,6 +80,7 @@ spec:
           
           # Post message        
           msgSent=0
+          msgFail=0
           for SLACK_INTEGRATION in $(cat /cd-config/toolchain.json | jq -c -r '.services[] | select (.service_id=="slack") '"${SELECT_DOMAIN}"' | (.parameters) | ({"webhook":.api_token, "channel":.channel_name})')
           do
             WEBHOOK=$(echo ${SLACK_INTEGRATION} | jq -r ' .webhook')
@@ -102,15 +103,16 @@ spec:
               msgSent=$((msgSent+1))
             else
               echo "Failed to post the message to Slack."
-              echo "Exiting: ${msgSent} message(s) posted to Slack."
-              exit $exitStatus          
+              # keep track of failures
+              msgFail=$((msgFail+1))
             fi
             if [ "$SLACK_CHANNEL" ]; then
               # don't send the same message more than once if channel was specified
               break
             fi
           done
-          echo "Done: ${msgSent} message(s) posted to Slack."
+          echo "Done: ${msgSent} message(s) posted to Slack (${msgFail} failures)."
+          exit $exitStatus
       volumeMounts:
         - mountPath: /steps
           name: steps-volume
