Handle exit based on error if any

diff --git a/communication/task-post-slack.yaml b/communication/task-post-slack.yaml
--- a/communication/task-post-slack.yaml
+++ b/communication/task-post-slack.yaml
@@ -112,7 +112,11 @@ spec:
             fi
           done
           echo "Done: ${msgSent} message(s) posted to Slack (${msgFail} failures)."
-          exit $exitStatus
+          
+          # Handle exit based on error if any
+          if [ $msgFail -ne 0  && "$(inputs.params.exitOnError)" == "true"]; then
+            exit 1
+          fi           
       volumeMounts:
         - mountPath: /steps
           name: steps-volume
