fix indentation

diff --git a/communication/task-post-slack.yaml b/communication/task-post-slack.yaml
--- a/communication/task-post-slack.yaml
+++ b/communication/task-post-slack.yaml
@@ -80,29 +80,34 @@ spec:
           echo "Retrieving Slack webhook(s) for $SLACK_DOMAIN domain."
           msgSent=0
           for SLACK_INTEGRATION in $(cat /cd-config/toolchain.json | jq -c -r '.services[] | select (.service_id=="slack") | select (.parameters.team_url=="'"${SLACK_DOMAIN}"'") | (.parameters) | ({"webhook":.api_token, "channel":.channel_name})')
-            do
-              WEBHOOK=$(echo ${SLACK_INTEGRATION} | jq -r ' .webhook')
-              if [[ "$(inputs.params.messageFormat)" == "text" ]]; then
-                if [ "$SLACK_CHANNEL" ]; then
-                  CHANNEL=$SLACK_CHANNEL
-                  echo "Using channel $CHANNEL as passed as parameter."
-                else
-                  CHANNEL=$(echo ${SLACK_INTEGRATION} | jq -r ' .channel')
-                  echo "Using channel $CHANNEL as defined in Slack integration."
-                fi
-                # format message to a Slack JSON payload
-                # echo "Formatting text message to JSON."
-                echo '{"channel": "'"${CHANNEL}"'", "type": "text"}' | jq --rawfile text /steps/message.content '.text=$text' > /steps/payload.json
-              fi
-              echo "Slack Message payload:"
-              cat /steps/payload.json
-              echo "Posting Slack Message using Webhook $WEBHOOK."
-              if [ $(curl -X POST -H 'Content-type: application/json' -d @/steps/payload.json -o /dev/null -w "%{http_code}" "$WEBHOOK") = 200 ]; then
-                msgSent=$((msgSent+1))
+          do
+            WEBHOOK=$(echo ${SLACK_INTEGRATION} | jq -r ' .webhook')
+            if [[ "$(inputs.params.messageFormat)" == "text" ]]; then
+              if [ "$SLACK_CHANNEL" ]; then
+                CHANNEL=$SLACK_CHANNEL
+                echo "Using channel $CHANNEL as passed as parameter."                  
               else
-                echo "Failed to post the message to Slack. Exiting...." 
-                exit $exitStatus          
-             fi
+                CHANNEL=$(echo ${SLACK_INTEGRATION} | jq -r ' .channel')
+                echo "Using channel $CHANNEL as defined in Slack integration."
+              fi
+              # format message to a Slack JSON payload
+              # echo "Formatting text message to JSON."
+              echo '{"channel": "'"${CHANNEL}"'", "type": "text"}' | jq --rawfile text /steps/message.content '.text=$text' > /steps/payload.json
+            fi
+            echo "Slack Message payload:"
+            cat /steps/payload.json
+            echo "Posting Slack Message using Webhook $WEBHOOK."
+            if [ $(curl -X POST -H 'Content-type: application/json' -d @/steps/payload.json -o /dev/null -w "%{http_code}" "$WEBHOOK") = 200 ]; then
+              msgSent=$((msgSent+1))
+            else
+              echo "Failed to post the message to Slack."
+              echo "Exiting: ${msgSent} message(s) posted to Slack."
+              exit $exitStatus          
+            fi
+            if [ "$SLACK_CHANNEL" ]; then
+              # don't send the same message more than once if channel was specified
+              break
+            fi
           done
           echo "Done: ${msgSent} message(s) posted to Slack."
       volumeMounts:
