Update task-bom.yaml

diff --git a/cra/task-bom.yaml b/cra/task-bom.yaml
--- a/cra/task-bom.yaml
+++ b/cra/task-bom.yaml
@@ -286,16 +286,27 @@ spec:
 
           echo "$(params.repository)"
           echo "$(params.scm-type)"
-          if [ "$(params.repository)" == *"git.cloud.ibm.com"* ] && [ "$(params.scm-type)" != "gitlab" ]; then
-            echo "Error: Trigger type '$(params.scm-type)' expected to be gitlab"
-            exit 1
-          elif [ "$(params.repository)" == *"ibm.com"* ] && [ "$(params.scm-type)" != "github-ent" ]; then
-            echo "Error: Trigger type '$(params.scm-type)' expected to be github-ent"
-            exit 1
-          elif [ "$(params.scm-type)" != "github" ]; then
-            echo "Error: Trigger type '$(params.scm-type)' expected to be github"
-            exit 1
-          fi
+          case "$(params.repository)" in
+            *git.cloud.ibm.com*)
+            if [ "$(params.scm-type)" != "gitlab" ]; then
+              echo "Error: Trigger type '$(params.scm-type)' expected to be gitlab"
+              exit 1
+            fi
+            ;;
+          *ibm.com*)
+            if [ "$(params.scm-type)" != "github-ent" ]; then
+              echo "Error: Trigger type '$(params.scm-type)' expected to be github-ent"
+              exit 1
+            fi
+            ;;
+          *)
+            if [ "$(params.scm-type)" != "github" ]; then
+              echo "Error: Trigger type '$(params.scm-type)' expected to be github"
+              exit 1
+            fi
+            ;;
+          esac
+
 
           /usr/local/bin/comm-editor \
             -repo-url "$(params.repository)" \
